# DLMP Secret配置
# 数据库密码、JWT密钥、API密钥等敏感信息

apiVersion: v1
kind: Secret
metadata:
  name: dlmp-database-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: Opaque
data:
  # 数据库配置 (base64编码)
  DB_USERNAME: ZGxtcA==           # dlmp
  DB_PASSWORD: ZGxtcDEyMzQ1Ng==   # dlmp123456
  DB_ROOT_PASSWORD: cm9vdDEyMzQ1Ng== # root123456

---
apiVersion: v1
kind: Secret
metadata:
  name: dlmp-redis-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: Opaque
data:
  # Redis配置 (base64编码)
  REDIS_PASSWORD: cmVkaXMxMjM0NTY=  # redis123456

---
apiVersion: v1
kind: Secret
metadata:
  name: dlmp-app-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: Opaque
data:
  # 应用配置 (base64编码)
  JWT_SECRET: ZGxtcC1qd3Qtc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbi1lbnZpcm9ubWVudA== # dlmp-jwt-secret-key-for-production-environment
  ENCRYPTION_KEY: ZGxtcC1lbmNyeXB0aW9uLWtleS0yMDIz  # dlmp-encryption-key-2023
  API_SECRET_KEY: ZGxtcC1hcGktc2VjcmV0LWtleS0yMDIz  # dlmp-api-secret-key-2023

---
apiVersion: v1
kind: Secret
metadata:
  name: dlmp-monitoring-secret
  namespace: dlmp-monitoring
  labels:
    app: prometheus
    environment: production
type: Opaque
data:
  # 监控系统配置
  GRAFANA_ADMIN_PASSWORD: YWRtaW4xMjM0NTY=  # admin123456
  ALERT_WEBHOOK_URL: aHR0cDovL3dlYmhvb2stc2VydmVyOjgwODAvYWxlcnRz  # webhook URL
  SMTP_PASSWORD: c210cC1wYXNzd29yZA==  # smtp-password

---
# TLS证书Secret
apiVersion: v1
kind: Secret
metadata:
  name: dlmp-tls-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: kubernetes.io/tls
data:
  # TLS证书和私钥 (需要替换为实际证书)
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lKQUxGM01PcXIydDMrTUEwR0NTcUdTSWIzRFFFQkN3VUFNRVl4Q3pBSkJnTlYKQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpEUVRFUE1BMEdBMVVFQnd3R1EyRnViMjVqTVJZd0ZBWURWUVFIREExVAphVzVwZUNCUllXMUJiR0Z1TUMwR0ExVUVDZ3dnUW5KdloyOTJBZy0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzVuOFA4aStETGhxdEIKQUNjNU03cFZxTjFSdWlkSTJGNElhOTQweDRVaXFOOWVNZGZvK25sOC9hYS0tLS0tLS0tLS0tLS0tLS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

---
# Docker镜像拉取Secret
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5leGFtcGxlLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogImRsbXAtdXNlciIsCiAgICAgICJwYXNzd29yZCI6ICJkbG1wLXBhc3N3b3JkIiwKICAgICAgImF1dGgiOiAiWkd4dGNDMTFjMlZ5T21Sc2JYQXRjR0Z6YzNkdmNtUT0iCiAgICB9CiAgfQp9

---
# 数据库初始化脚本Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-init-script
  namespace: dlmp-production
  labels:
    app: mysql
    environment: production
type: Opaque
data:
  init.sql: |
    Q1JFQVRFIERBVEFCQVNFIElGIE5PVCBFWELTVFMTZG1scCBERUZBVUxUIENIQVJBQ1RFUiBTRVQgdXRmOG1iNCBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaTsKCkNSRUFURSBVU0VSIElGIE5PVCBFWELHSVRTIFF1ZGxtcCRAJyUbJyBJREVOVElGSUVEIEJZICdkbG1wMTIzNDU2JzsKR1JBTlQgQUxMIFBSSVZJTEVHRVMgT04gZGxtcC4qIFRPICdkbG1wJ0AnJSc7CkZMVVNIIFBSSVZJTEVHRVM7

---
# LDAP/AD认证Secret (如果使用)
apiVersion: v1
kind: Secret
metadata:
  name: ldap-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: Opaque
data:
  LDAP_URL: bGRhcDovL2xkYXAuZXhhbXBsZS5jb206Mzg5  # ldap://ldap.example.com:389
  LDAP_BASE_DN: ZGM9ZXhhbXBsZSxkYz1jb20=  # dc=example,dc=com
  LDAP_USERNAME: Y249YWRtaW4sZGM9ZXhhbXBsZSxkYz1jb20=  # cn=admin,dc=example,dc=com
  LDAP_PASSWORD: bGRhcC1hZG1pbi1wYXNzd29yZA==  # ldap-admin-password

---
# 第三方服务API密钥
apiVersion: v1
kind: Secret
metadata:
  name: external-api-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: Opaque
data:
  # 短信服务API密钥
  SMS_ACCESS_KEY: c21zLWFjY2Vzcy1rZXk=  # sms-access-key
  SMS_SECRET_KEY: c21zLXNlY3JldC1rZXk=   # sms-secret-key
  
  # 邮件服务配置
  EMAIL_USERNAME: ZW1haWxAZXhhbXBsZS5jb20=  # email@example.com
  EMAIL_PASSWORD: ZW1haWwtcGFzc3dvcmQ=      # email-password
  
  # 对象存储配置
  OSS_ACCESS_KEY: b3NzLWFjY2Vzcy1rZXk=     # oss-access-key
  OSS_SECRET_KEY: b3NzLXNlY3JldC1rZXk=     # oss-secret-key
  
  # 支付服务配置
  PAYMENT_API_KEY: cGF5bWVudC1hcGkta2V5    # payment-api-key
  PAYMENT_SECRET: cGF5bWVudC1zZWNyZXQ=     # payment-secret

---
# Webhook认证Secret
apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: Opaque
data:
  WEBHOOK_SECRET: d2ViaG9vay1zZWNyZXQtMjAyMw==  # webhook-secret-2023
  GITHUB_WEBHOOK_SECRET: Z2l0aHViLXdlYmhvb2stc2VjcmV0  # github-webhook-secret

---
# SSL证书颁发机构Secret
apiVersion: v1
kind: Secret
metadata:
  name: ca-secret
  namespace: dlmp-production
  labels:
    app: dlmp
    environment: production
type: Opaque
data:
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZhekNDQTFPZ0F3SUJBZ0lVQVBOdXgvNTNlWHh2ODBacmV2M0ZOMjl0LzE0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNRVXN4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TURNRE1qSXdPVFF4TXpGYUZ3MHlOREF6Ck1qRXdPVFF4TXpGYU1FVXhDekFKQmdOVkJBWVRBa0ZBT0DQUOAo---
  ca.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2tBZ0VBQW9JQkFRREExY1Jnd2R3eFZBdmkKN1U4aWx1cnBUMGZnWWJ3T1ZSNFU1dnEyVDB4Z1c5Q1M3SGR2RmNoUzEwRjdWK055VGQ3Z0Y4VWZOZz0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==