# Filebeat配置文件
# DLMP日志收集配置

# ==================== Filebeat输入配置 ====================
filebeat.inputs:
  # Nginx访问日志
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
      - /var/log/nginx/*.access.log
    fields:
      service: nginx
      log_type: access
      environment: ${ENVIRONMENT:production}
    fields_under_root: true
    multiline.pattern: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
    multiline.negate: true
    multiline.match: after
    scan_frequency: 10s
    harvester_buffer_size: 16384
    max_bytes: 10485760

  # Nginx错误日志
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/error.log
      - /var/log/nginx/*.error.log
    fields:
      service: nginx
      log_type: error
      environment: ${ENVIRONMENT:production}
    fields_under_root: true
    multiline.pattern: '^\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}'
    multiline.negate: true
    multiline.match: after

  # DLMP后端应用日志
  - type: log
    enabled: true
    paths:
      - /var/log/dlmp/application.log
      - /var/log/dlmp/application-*.log
    fields:
      service: dlmp-backend
      log_type: application
      environment: ${ENVIRONMENT:production}
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
    multiline.negate: true
    multiline.match: after
    exclude_lines: ['^DEBUG', '^TRACE']

  # DLMP错误日志
  - type: log
    enabled: true
    paths:
      - /var/log/dlmp/error.log
    fields:
      service: dlmp-backend
      log_type: error
      environment: ${ENVIRONMENT:production}
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
    multiline.negate: true
    multiline.match: after

  # DLMP业务日志
  - type: log
    enabled: true
    paths:
      - /var/log/dlmp/business.log
    fields:
      service: dlmp-backend
      log_type: business
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # DLMP性能日志
  - type: log
    enabled: true
    paths:
      - /var/log/dlmp/performance.log
    fields:
      service: dlmp-backend
      log_type: performance
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # MySQL慢查询日志
  - type: log
    enabled: true
    paths:
      - /var/log/mysql/slow.log
      - /var/log/mysql/mysql-slow.log
    fields:
      service: mysql
      log_type: slow-query
      environment: ${ENVIRONMENT:production}
    fields_under_root: true
    multiline.pattern: '^# Time:'
    multiline.negate: true
    multiline.match: after

  # MySQL错误日志
  - type: log
    enabled: true
    paths:
      - /var/log/mysql/error.log
      - /var/log/mysql/mysqld.log
    fields:
      service: mysql
      log_type: error
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # Redis日志
  - type: log
    enabled: true
    paths:
      - /var/log/redis/redis.log
      - /var/log/redis/redis-server.log
    fields:
      service: redis
      log_type: server
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # 系统日志
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/messages
    fields:
      service: system
      log_type: syslog
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # Docker容器日志
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

  # Kubernetes Pod日志
  - type: log
    enabled: false
    paths:
      - /var/log/pods/*/*/*.log
    fields:
      service: kubernetes
      log_type: pod
    fields_under_root: true
    processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/pods/"

# ==================== 处理器配置 ====================
processors:
  # 添加主机信息
  - add_host_metadata:
      when.not.contains.tags: forwarded
      
  # 添加Docker元数据
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      
  # 添加进程信息
  - add_process_metadata:
      match_pids: ['process.pid', 'process.parent.pid']
      target: process
      
  # 删除敏感字段
  - drop_fields:
      fields: ["host.mac", "host.ip"]
      ignore_missing: true
      
  # 重命名字段
  - rename:
      fields:
        - from: "agent.hostname"
          to: "host_name"
      ignore_missing: true
      
  # 添加自定义标签
  - add_tags:
      tags: [dlmp, filebeat]
      when:
        not:
          contains:
            tags: dlmp

# ==================== 输出配置 ====================
output.logstash:
  hosts: ["logstash:5044"]
  
  # 负载均衡
  loadbalance: true
  
  # 压缩
  compression_level: 3
  
  # 超时配置
  timeout: 30
  
  # 批量设置
  bulk_max_size: 1024
  
  # 重试配置
  max_retries: 3
  backoff.init: 1s
  backoff.max: 60s

# 备用输出到Kafka
#output.kafka:
#  hosts: ["kafka:9092"]
#  topic: "dlmp-logs"
#  partition.round_robin:
#    reachable_only: false
#  required_acks: 1
#  compression: gzip
#  max_message_bytes: 1000000

# 备用输出到Redis
#output.redis:
#  hosts: ["redis-node-1:6379"]
#  password: "redis123456"
#  key: "dlmp:logs"
#  db: 0
#  timeout: 5s
#  max_retries: 3

# ==================== 日志配置 ====================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
  interval: 24h
  rotateeverybytes: 10485760

# ==================== 监控配置 ====================
monitoring.enabled: true
http.enabled: true
http.host: 0.0.0.0
http.port: 5066

# ==================== 性能配置 ====================
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 1s

# ==================== 安全配置 ====================
# 如果使用TLS
#output.logstash:
#  ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
#  ssl.certificate: "/etc/pki/client/cert.pem"
#  ssl.key: "/etc/pki/client/cert.key"

# ==================== 模板配置 ====================
setup.template.settings:
  index.number_of_shards: 3
  index.number_of_replicas: 1
  index.refresh_interval: 5s
  index.mapping.total_fields.limit: 10000

# ==================== ILM配置 ====================
setup.ilm.enabled: true
setup.ilm.rollover_alias: "filebeat"
setup.ilm.pattern: "{now/d}-000001"
setup.ilm.policy: "filebeat-policy"

# ==================== 自动重新加载配置 ====================
filebeat.config.inputs:
  enabled: true
  path: configs/*.yml
  reload.enabled: true
  reload.period: 10s

# ==================== 字段过滤 ====================
processors:
  - include_fields:
      fields: ["@timestamp", "message", "service", "log_type", "level", "host", "source"]
  - drop_event:
      when:
        or:
          - contains:
              message: "health"
          - contains:
              message: "metrics"
          - regexp:
              message: '^$'