# DLMP系统告警规则
# 包含系统、应用、业务等各层面的告警规则

groups:
  # 系统资源告警
  - name: system-alerts
    rules:
      # CPU使用率过高
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "高CPU使用率告警"
          description: "实例 {{ $labels.instance }} CPU使用率为 {{ $value | humanizePercentage }}，超过80%阈值"

      # 内存使用率过高
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "高内存使用率告警"
          description: "实例 {{ $labels.instance }} 内存使用率为 {{ $value | humanizePercentage }}，超过85%阈值"

      # 磁盘使用率过高
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "高磁盘使用率告警"
          description: "实例 {{ $labels.instance }} 磁盘 {{ $labels.mountpoint }} 使用率为 {{ $value | humanizePercentage }}，超过85%阈值"

      # 磁盘使用率严重过高
      - alert: CriticalDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 95
        for: 2m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "严重磁盘使用率告警"
          description: "实例 {{ $labels.instance }} 磁盘 {{ $labels.mountpoint }} 使用率为 {{ $value | humanizePercentage }}，超过95%阈值"

      # 系统负载过高
      - alert: HighSystemLoad
        expr: node_load1 / count by(instance) (node_cpu_seconds_total{mode="idle"}) > 0.8
        for: 10m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "高系统负载告警"
          description: "实例 {{ $labels.instance }} 1分钟负载为 {{ $value }}，超过CPU核心数的80%"

      # 节点离线
      - alert: NodeDown
        expr: up{job="node-exporter"} == 0
        for: 2m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "节点离线告警"
          description: "节点 {{ $labels.instance }} 已离线超过2分钟"

  # 应用服务告警
  - name: application-alerts
    rules:
      # 应用服务不可用
      - alert: ServiceDown
        expr: up{job="dlmp-backend"} == 0
        for: 1m
        labels:
          severity: critical
          category: application
        annotations:
          summary: "应用服务不可用"
          description: "DLMP后端服务 {{ $labels.instance }} 不可用"

      # 应用响应时间过长
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="dlmp-backend"}[5m])) > 3
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "应用响应时间过长"
          description: "DLMP后端服务 {{ $labels.instance }} 95%分位响应时间为 {{ $value }}s，超过3s阈值"

      # HTTP错误率过高
      - alert: HighErrorRate
        expr: rate(http_requests_total{job="dlmp-backend",status=~"5.."}[5m]) / rate(http_requests_total{job="dlmp-backend"}[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "HTTP错误率过高"
          description: "DLMP后端服务 {{ $labels.instance }} 5xx错误率为 {{ $value | humanizePercentage }}，超过5%阈值"

      # JVM堆内存使用率过高
      - alert: HighJVMHeapUsage
        expr: jvm_memory_used_bytes{area="heap",job="dlmp-backend"} / jvm_memory_max_bytes{area="heap",job="dlmp-backend"} * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "JVM堆内存使用率过高"
          description: "DLMP后端服务 {{ $labels.instance }} JVM堆内存使用率为 {{ $value | humanizePercentage }}，超过80%阈值"

      # GC时间过长
      - alert: HighGCTime
        expr: rate(jvm_gc_collection_seconds_sum{job="dlmp-backend"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "GC时间过长告警"
          description: "DLMP后端服务 {{ $labels.instance }} GC时间占比为 {{ $value | humanizePercentage }}，超过10%阈值"

      # 线程数过多
      - alert: HighThreadCount
        expr: jvm_threads_current{job="dlmp-backend"} > 1000
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "线程数过多告警"
          description: "DLMP后端服务 {{ $labels.instance }} 当前线程数为 {{ $value }}，超过1000阈值"

  # 数据库告警
  - name: database-alerts
    rules:
      # MySQL服务不可用
      - alert: MySQLDown
        expr: up{job="mysql-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          category: database
        annotations:
          summary: "MySQL服务不可用"
          description: "MySQL数据库 {{ $labels.instance }} 不可用"

      # MySQL连接数过多
      - alert: MySQLHighConnections
        expr: mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "MySQL连接数过多"
          description: "MySQL数据库 {{ $labels.instance }} 连接数使用率为 {{ $value | humanizePercentage }}，超过80%阈值"

      # MySQL慢查询过多
      - alert: MySQLHighSlowQueries
        expr: rate(mysql_global_status_slow_queries[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "MySQL慢查询过多"
          description: "MySQL数据库 {{ $labels.instance }} 慢查询率为 {{ $value }}/s，超过0.1/s阈值"

      # Redis服务不可用
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          category: database
        annotations:
          summary: "Redis服务不可用"
          description: "Redis服务 {{ $labels.instance }} 不可用"

      # Redis内存使用率过高
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "Redis内存使用率过高"
          description: "Redis服务 {{ $labels.instance }} 内存使用率为 {{ $value | humanizePercentage }}，超过80%阈值"

      # Redis连接数过多
      - alert: RedisHighConnections
        expr: redis_connected_clients > 1000
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "Redis连接数过多"
          description: "Redis服务 {{ $labels.instance }} 连接数为 {{ $value }}，超过1000阈值"

  # 网络和负载均衡告警
  - name: network-alerts
    rules:
      # 网站不可访问
      - alert: WebsiteDown
        expr: probe_success{job="blackbox-http"} == 0
        for: 1m
        labels:
          severity: critical
          category: network
        annotations:
          summary: "网站不可访问"
          description: "网站 {{ $labels.instance }} 无法访问"

      # 网站响应时间过长
      - alert: WebsiteSlowResponse
        expr: probe_duration_seconds{job="blackbox-http"} > 5
        for: 5m
        labels:
          severity: warning
          category: network
        annotations:
          summary: "网站响应时间过长"
          description: "网站 {{ $labels.instance }} 响应时间为 {{ $value }}s，超过5s阈值"

      # SSL证书即将过期
      - alert: SSLCertificateExpiry
        expr: probe_ssl_earliest_cert_expiry{job="blackbox-http"} - time() < 86400 * 30
        for: 1h
        labels:
          severity: warning
          category: network
        annotations:
          summary: "SSL证书即将过期"
          description: "网站 {{ $labels.instance }} SSL证书将在 {{ $value | humanizeDuration }} 后过期"

      # 网络丢包率过高
      - alert: HighPacketLoss
        expr: rate(node_network_receive_drop_total[5m]) + rate(node_network_transmit_drop_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
          category: network
        annotations:
          summary: "网络丢包率过高"
          description: "实例 {{ $labels.instance }} 网络接口 {{ $labels.device }} 丢包率为 {{ $value }} 包/s"

  # 业务告警
  - name: business-alerts
    rules:
      # 案件处理积压
      - alert: CaseBacklog
        expr: dlmp_cases_pending_total > 1000
        for: 10m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "案件处理积压告警"
          description: "待处理案件数量为 {{ $value }}，超过1000件阈值"

      # 用户登录失败率过高
      - alert: HighLoginFailureRate
        expr: rate(dlmp_login_failures_total[5m]) / rate(dlmp_login_attempts_total[5m]) * 100 > 20
        for: 5m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "用户登录失败率过高"
          description: "用户登录失败率为 {{ $value | humanizePercentage }}，超过20%阈值"

      # 支付处理异常
      - alert: PaymentProcessingError
        expr: rate(dlmp_payment_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          category: business
        annotations:
          summary: "支付处理异常告警"
          description: "支付处理错误率为 {{ $value }}/s，超过0.1/s阈值"

      # 文件上传失败率过高
      - alert: HighFileUploadFailureRate
        expr: rate(dlmp_file_upload_failures_total[5m]) / rate(dlmp_file_upload_attempts_total[5m]) * 100 > 10
        for: 5m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "文件上传失败率过高"
          description: "文件上传失败率为 {{ $value | humanizePercentage }}，超过10%阈值"

  # 容器和编排告警
  - name: container-alerts
    rules:
      # 容器重启过于频繁
      - alert: ContainerRestartLoop
        expr: rate(container_restart_count[1h]) * 3600 > 5
        for: 5m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "容器重启过于频繁"
          description: "容器 {{ $labels.name }} 在过去1小时内重启了 {{ $value }} 次"

      # 容器CPU使用率过高
      - alert: ContainerHighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "容器CPU使用率过高"
          description: "容器 {{ $labels.name }} CPU使用率为 {{ $value | humanizePercentage }}，超过80%阈值"

      # 容器内存使用率过高
      - alert: ContainerHighMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "容器内存使用率过高"
          description: "容器 {{ $labels.name }} 内存使用率为 {{ $value | humanizePercentage }}，超过80%阈值"